name: status_shop
description: "Android and IOS app for Status Shop."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # firebase removed

  connectivity_plus: ^7.0.0
  path_provider: ^2.1.4
  shared_preferences: ^2.3.0
  intl: ^0.20.2
  image_picker: ^1.1.1

  flutter_localizations:
    sdk: flutter

  provider: ^6.0.5
  http: ^1.2.0

  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_launcher_icons: ^0.13.1
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter_icons:
  android: true
  ios: true
  image_path: "assets/images/icon.png"

flutter:
  uses-material-design: true
  generate: true

  assets:
    - assets/images/logo.png
    - assets/images/sale_banner.png
    - assets/images/
    - assets/vinill/pu/
    - assets/vinill/
    - assets/vinill/pvc/
    - assets/vinill/glitter/
    - assets/vinill/metalic/
    - assets/vinill/reflective/
    - assets/vinill/stretch/
    - assets/vinill/flock/

l10n:
  arb-dir: lib/l10n
  template-arb-file: app_en.arb
  output-localization-file: app_localizations.dart
